### ISSUE TITLE
get rid of zero argument MCVISolver constructor

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCVI.jl#6]
@rejuvyesh can we get rid of the zero argument MCVISolver constructor [here](https://github.com/JuliaPOMDP/MCVI.jl/blob/ce9b27927e2fc051dfb00eff2aea66f74b8362f1/src/solver.jl#L59)?

If someone uses it, they just run into "undefined" errors that are hard to understand, so, unless there is another reason for it, I think getting rid of it would be the best for usability.

**Comment by zsunberg** [comment]
@ekhlassonu and I did this and we were confused

**Comment by rejuvyesh** [comment]
I see. Sure. Not completely sure why I allowed it. I guess was an even worse julia noob then.
